# Generated by Django 3.1.4 on 2020-12-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('first_author', models.CharField(max_length=30)),
                ('cited_by', models.CharField(blank=True, max_length=20, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
